### ISSUE TITLE
Error when typing path

### ISSUE THREAD

**Issue by blephy** [jrdrg/eslint-plugin-sort-exports#30]
Hi,

I have this error in VSCode while typing export statement. The error occurred when the path from the module is an empty string.

```txt
TypeError: Cannot read properties of undefined (reading '0')
Occurred while linting /Users/*****/projects/perso/****/src/index.ts:2
Rule: "sort-exports/sort-exports"
    at checkDeclaration (/Users/*****/projects/perso/****/node_modules/eslint-plugin-sort-exports/lib/sortExports.js:126:55)
    at ExportAllDeclaration (/Users/*****/projects/perso/****/node_modules/eslint-plugin-sort-exports/lib/sortExports.js:163:9)
    at ruleErrorHandler (/Users/*****/projects/perso/****/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /Users/*****/projects/perso/****/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/*****/projects/perso/****/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/*****/projects/perso/****/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/*****/projects/perso/****/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/Users/*****/projects/perso/****/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/Users/*****/projects/perso/****/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
```

**Comment by jrdrg** [comment]
Hi @blephy - can you try v0.7.0 and see if it fixes the issue? This might have been due to a missing null check/default value which I think may have been fixed judging by the stack trace you pasted. If that doesn't do it, could you provide more repro steps/details?

**Comment by blephy** [comment]
Hi @jrdrg 

This is resolved 👍🏼
